window.DASHBOARD_DATA = {
  meta: {
    version: "2.0",
    generated_at: "2026-07-20 02:25",
    brand_short: "菜",
    brand_long: "CAI-OS",
    greeting: "向上",
    owner: "一棵菜"
  },

  // ================= 4 个领域（左侧侧栏 + 底部仪表盘） =================
  // ================= 待办清单（大 TODO 台账，独立于项目卡） =================
  todo_master: {
    intro: "",
      sop: [],
      review_cycle: "",
      progress_status: "",
      id: "p-04",
    name: "待办清单（大 TODO 台账）",
    subtasks: [
      { title: "✅ SYV 研究流程", done: true },
      { title: "✅ 苹果订阅取消", done: true },
      { title: "META-01 荷兰求职工签（12 动作拆解）", done: false },
      { title: "✅ AI 副业变现体系（已出 v1）", done: true },
      { title: "💤 夏鹏职场课重构（暂缓冻结）", done: false },
      { title: "✅ FrieslandCampina BA Portal 直投", done: true },
      { title: "✅ Stolt Manager LinkedIn 冷触达", done: true },
      { title: "✅ 30 家清单补 8-10 家", done: true },
      { title: "✅ Recommendation 邮件截图入档", done: true },
      { title: "✅ Elevator Speech 平衡版 v0.2 归档", done: true },
      { title: "✅ Q01 STAR 答题", done: true },
      { title: "✅ Q04 PREP+FABE 答题", done: true },
      { title: "09-07 前累计 40+ 投递", done: false },
      { title: "10-07 前累计 60+ 投递", done: false },
      { title: "AI 副业拆解方案 v1 起草", done: false },
      { title: "💤 盘点夏鹏课模块结构（冻结）", done: false },
      { title: "💤 定夏鹏课每周一个模块输出机制（冻结）", done: false }
    ]
  },

  domains: [
    { id: "d-sage", name: "求职学习", color_token: "sage", icon_glyph: "求" },
    { id: "d-blue", name: "思考表达", color_token: "blue", icon_glyph: "思" },
    { id: "d-pink", name: "自我成长", color_token: "pink", icon_glyph: "我" },
    { id: "d-sand", name: "生活运营", color_token: "sand", icon_glyph: "生" }
  ],

  // ================= 今日时间轴（空，等你填装） =================
  timeline: [],

  // ================= 今日任务池（空，等你从大台账挑今日事项） =================
  tasks: [],

  // ================= 习惯（本轮先不放，后续再加） =================
  habits: [],

  // ================= 收件箱 / 待澄清 =================
  inbox: [],

  // ================= 项目（19 个 + 大 TODO） =================
  projects: [
    {
      intro: "个人知识库/武器库。记录读书、博客、见闻中产生的思考，以卡片盒方式归档，形成结构化的思想资产。",
      sop: ["读书/看博客/日常见闻中产生思考", "提炼核心观点与洞察", "卡片盒归档", "按需调用与关联"],
      review_cycle: "不强制，仅在主动提出时进行",
      progress_status: "SOP 和方法论已完成，有序使用中",
      id: "p-01",
      category: "学习",
      name: "书籍+播客+见闻→思考",
      short_label: "书",
      domain: "d-blue",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "blue",
      waiting: []
    },
    {
      intro: "个人穿搭知识库。投喂形象管理资料后形成方法论，随时对话问答（如今天穿什么、某单品怎么搭）。",
      sop: ["持续投喂形象资料（图片/文字/链接）", "整理形成个人穿搭方法论", "日常对话提问，从资料库中提取答案"],
      review_cycle: "暂不需要",
      progress_status: "刚启动，资料投喂中",
      id: "p-02",
      category: "其他",
      name: "形象管理",
      short_label: "形",
      domain: "d-pink",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "pink",
      waiting: []
    },
    {
      intro: "求职全流程支持系统。覆盖 CV / Cover Letter / JD 拆解 / 面试模拟 / Networking 准备。",
      sop: ["拿到 JD → 拆解岗位核心需求", "根据 JD 定制 CV 和 Cover Letter", "模拟面试准备（STAR / 行为题）", "Networking 触达准备", "投递后追踪复盘", "每周复盘迭代"],
      review_cycle: "每周",
      progress_status: "已投递 8 份简历（截至 07-19）",
      id: "p-03",
      category: "求职",
      name: "求职底层世界观",
      short_label: "求",
      domain: "d-sage",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sage",
      waiting: []
    },
    {
      intro: "目标拆解与方法论沉淀系统。给目标后辅助拆解计划，核心资产是不断迭代更新的拆解方法论。",
      sop: ["抛出目标/任务", "辅助拆解为可执行步骤", "拆解过程中发现问题，反馈更新资料", "持续迭代拆解方法论", "每 15 天复盘"],
      review_cycle: "每 15 天",
      progress_status: "方法论和 SOP 已完成",
      id: "p-05",
      category: "工具",
      name: "拆解一切",
      short_label: "拆",
      domain: "d-blue",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "blue",
      waiting: []
    },
    {
      intro: "个人饮食管理系统。根据投喂的资料形成营养方法论，每天排食谱和采购清单，按预算记录每日饮食与购买情况。",
      sop: ["投喂饮食/营养资料，形成个人饮食方法论", "每天排定食谱和采购清单", "按预算记录每日购买和饮食情况", "每 10 天复盘一次饮食与开支"],
      review_cycle: "每 10 天",
      progress_status: "已完成第一轮食谱使用，反馈良好",
      id: "p-06",
      category: "其他",
      name: "健康饮食",
      short_label: "健",
      domain: "d-sand",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sand",
      waiting: []
    },
    {
      intro: "个人记账与财务管理。日常记录收支，投喂理财资料形成方法论，按收入与支出两个维度归纳总结。",
      sop: ["日常口述记账", "投喂财务/理财资料，形成方法论", "按收入与支出进行归纳总结", "每 10 天复盘消费与财务健康度"],
      review_cycle: "每 10 天",
      progress_status: "以记账为主，方法论尚未建立",
      id: "p-07",
      category: "其他",
      name: "财富中心",
      short_label: "财",
      domain: "d-sand",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sand",
      waiting: []
    },
    {
      intro: "个人想法收纳系统。用卡片盒方法将每一个想法收纳、整理、归类，形成结构化的思想资产。",
      sop: ["用户抛出想法或灵感", "收纳、整理、归类", "卡片盒归档", "月度复盘整合"],
      review_cycle: "每月",
      progress_status: "方法论和流程已确定完成",
      id: "p-09",
      category: "自我",
      name: "我的美好人生",
      short_label: "美",
      domain: "d-pink",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "pink",
      waiting: []
    },
    {
      intro: "逻辑表达能力锻炼系统。投喂参考资料形成方法论，通过日常练习提升逻辑思维与表达清晰度。",
      sop: ["投喂逻辑/表达相关参考资料", "形成个人方法论", "日常练习（提问、回答、写作）", "月度复盘迭代"],
      review_cycle: "每月",
      progress_status: "方法论和 SOP 已完成",
      id: "p-10",
      category: "练习",
      name: "逻辑 & 表达",
      short_label: "逻",
      domain: "d-blue",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "blue",
      waiting: []
    },
    {
      intro: "英语日常陪练系统。通过日常对话练习保持英语语感和表达能力。",
      sop: ["日常英语对话练习", "记录常用表达和改进点", "月度复盘"],
      review_cycle: "每月",
      progress_status: "已建立，持续陪练中",
      id: "p-11",
      category: "学习",
      name: "English 日常陪练",
      short_label: "E陪",
      domain: "d-sage",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sage",
      waiting: []
    },
    {
      intro: "商业案例分析练习系统。从日常生活、新闻中感兴趣的商业现象出发，做深度案例分析，积累商业认知。",
      sop: ["发现感兴趣的商业现象/公司/模式", "抛出问题进行深度拆解", "形成案例分析文档归档", "月度复盘整合商业认知"],
      review_cycle: "每月",
      progress_status: "已完成 1 个案例（香港保险中介 CASE 001）",
      id: "p-12",
      category: "练习",
      name: "商业分析案例",
      short_label: "商",
      domain: "d-blue",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "blue",
      waiting: []
    },
    {
      intro: "AI 相关知识与技能的整理归纳系统。持续学习 AI 工具、方法论，形成结构化知识体系。",
      sop: ["持续学习 AI 工具与方法论", "收集扣子及其他项目中的 AI 相关推送内容", "整合归纳，补充进知识体系", "周复盘"],
      review_cycle: "每周",
      progress_status: "方法论和 SOP 已完成",
      id: "p-13",
      category: "学习",
      name: "AI 学习",
      short_label: "AI",
      domain: "d-sage",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sage",
      waiting: []
    },
    {
      intro: "个人日记收纳系统。用卡片盒方法对日常记录进行整理归类，形成结构化的生活档案。",
      sop: ["用户口述日记内容", "收纳、整理、归类", "卡片盒归档", "月度复盘整合"],
      review_cycle: "每月",
      progress_status: "方法论和流程已完成",
      id: "p-14",
      category: "自我",
      name: "日记 & 人生导师",
      short_label: "日",
      domain: "d-pink",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "pink",
      waiting: []
    },
    {
      intro: "英语学习整理归纳系统。整合私教课、友邻优课等资源，持续积累英语能力。",
      sop: ["私教课后做总结归档", "友邻优课每天跟读（一二五二法）", "阅读营/单词量 8 月再定", "月度复盘"],
      review_cycle: "每月",
      progress_status: "方法论和 SOP 已完成，正在执行中",
      id: "p-15",
      category: "学习",
      name: "English Learning",
      short_label: "E学",
      domain: "d-sage",
      stage: "3 板块并行推进中",
      next_step: "07-19 私教回放总结（最紧急）",
      deadline: null,
      subtasks: [
        { title: "🔥 07-19 私教回放做本次总结", done: false },
        { title: "友邻优课每天跟读计划（一二五二法）", done: false },
        { title: "后续每次私教课后都做总结（固化流程）", done: false },
        { title: "💤 阅读营 8 月开营再看是否加入", done: false },
        { title: "💤 单词量目标 8 月再定", done: false }
      ],
      progress_percent: null,
      color_token: "sage",
      waiting: []
    },
    {
      intro: "个人决策辅助系统。投喂参考资料提炼方法论，在需要做重要决策时提供结构化分析和辅导。",
      sop: ["投喂决策相关参考资料（书籍/框架/案例）", "沉淀为个人决策方法论", "遇到决策需求时调用方法论辅助分析", "月度复盘迭代"],
      review_cycle: "每月",
      progress_status: "方法论和 SOP 已完成",
      id: "p-16",
      category: "练习",
      name: "Decision Life",
      short_label: "D",
      domain: "d-blue",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "blue",
      waiting: []
    },
    {
      intro: "个人心理分析辅助系统。投喂参考资料形成方法论，在需要时辅助进行心理层面的分析与洞察。",
      sop: ["投喂心理学相关参考资料", "形成个人心理分析方法论", "有需求时调用方法论辅助分析", "月度复盘迭代"],
      review_cycle: "每月",
      progress_status: "方法论和 SOP 已完成",
      id: "p-17",
      category: "练习",
      name: "心理分析",
      short_label: "心",
      domain: "d-pink",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "pink",
      waiting: []
    },
    {
      intro: "国内职业机会资讯库。从小红书等平台收集感兴趣的国内职位/行业动态，用卡片盒方法整理归纳，作为荷兰求职的备选路径。",
      sop: [],
      review_cycle: "每月",
      progress_status: "方法论和 SOP 尚未完成",
      id: "p-18",
      category: "工具",
      name: "国内 backup",
      short_label: "备",
      domain: "d-sand",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sand",
      waiting: []
    },
    {
      intro: "职场问题应对系统。投喂职场相关资料沉淀方法论，遇到职场问题时调用方法论辅助解决。",
      sop: ["投喂职场相关参考资料", "形成个人职场方法论", "遇到职场问题时调用辅助", "月度复盘迭代"],
      review_cycle: "每月",
      progress_status: "方法论和 SOP 已完成",
      id: "p-19",
      category: "练习",
      name: "职场教练 skill",
      short_label: "职",
      domain: "d-sage",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "sage",
      waiting: []
    }
 ,
    {
      intro: "搭建和构建人生主体性的系统。整理和输入外在笔记，强化\"我\"在生活、决策、关系中的核心位置。",
      sop: ["用户抛出念头/想法", "以卡片盒方式拆解、整理、归类", "构建主体性认知框架", "每周复盘"],
      review_cycle: "每周",
      progress_status: "SOP 和方法论尚未搭建",
      id: "p-20",
      category: "自我",
      name: "主体性",
      short_label: "主",
      domain: "d-pink",
      stage: "规划中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "pink",
      waiting: []
    },
    {
      intro: "念头拆解与觉察系统。对用户抛出的每一个念头进行拆解分析，推动复盘、迭代与行动落地，以卡片盒方式记录。",
      sop: ["用户抛出念头", "拆解分析念头来源与结构", "复盘与迭代", "落地为具体行动", "以卡片盒形式归档记录"],
      review_cycle: "每周",
      progress_status: "工作流程已搭建完成，随时可接收念头进行拆解",
      id: "p-21",
      category: "自我",
      name: "觉察",
      short_label: "觉",
      domain: "d-pink",
      stage: "运行中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "pink",
      waiting: []
    },
    {
      intro: "人际交往能力提升系统。投喂资料沉淀方法论，根据实际场景和案例进行分析、拆解、归纳，辅助社交应对。",
      sop: ["投喂人际交往相关资料", "形成个人社交方法论", "遇到具体场景/案例时进行分析拆解", "每 15 天复盘迭代"],
      review_cycle: "每 15 天",
      progress_status: "方法论和 SOP 已完成",
      id: "p-22",
      category: "练习",
      name: "人际交往",
      short_label: "交",
      domain: "d-blue",
      stage: "构思中",
      next_step: "",
      deadline: null,
      subtasks: [],
      progress_percent: null,
      color_token: "blue",
      waiting: []
    }
  ]
};
